#!/bin/bash

#----------------------------------------------------------#
#                      Configuration                       #
#----------------------------------------------------------#

# Default values
KERNEL_VERSION="3.16.0-4-586"

#----------------------------------------------------------#
#                      Installation                        #
#----------------------------------------------------------#

apt-get --no-install-recommends --yes -qq install linux-image-$KERNEL_VERSION sudo \
    dosfstools parted rsync net-tools wireless-tools isc-dhcp-client ifupdown \
    openssh-client wget ca-certificates git-core make gcc bc nano

# Remove sudo password.
sed -i -E 's/^%sudo.+/%sudo ALL=(ALL) NOPASSWD: ALL/' /etc/sudoers

# Add a user
useradd -m -d /home/pi -s /bin/bash pi
adduser pi sudo
echo -e "raspberry\nraspberry\n" | passwd pi

# set root password
echo -e "raspberry\nraspberry\n" | passwd root
